dist: xenial
language: python
python:
    - 3.7
sudo: required
services:
    - docker
install:
    - pip install --upgrade pip
    - make dev-env
script:
    - set -e
    - if [ $(make n-docs-diff) -ne 0 ]; then make docs; fi;
    - if [ $(make n-other-diff) -ne 0 ]; then make build-test-all DARGS="--build-arg TEST_ONLY_BUILD=1"; fi;