name: "Build environment"
description: "Create build environment"

on: workflow_call

runs:
  steps:
    - name: Maximize build space 🛠
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
      shell: bash

    # Setup docker to build for multiple platforms, see:
    # https://github.com/docker/build-push-action/tree/master#usage
    # https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
    - name: Set up QEMU (for docker buildx) 🐳
      uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # dependabot updates to latest release

    # https://github.com/docker/build-push-action/tree/master#usage
    - name: Set up Docker Buildx (for multi-arch builds) 🐳
      uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # dependabot updates to latest release

    - name: Set Up Python 🐍
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install Dev Dependencies 📦
      run: |
        pip install --upgrade pip
        pip install -r requirements-dev.txt
      shell: bash
