name: Build and test Docker Images

on:
  schedule:
    # Weekly, at 03:00 on Monday UTC time
    - cron: "0 3 * * 1"
  pull_request:
    paths:
      - ".github/workflows/build-docker.yml"
      - ".github/actions/**"

      - "all-spark-notebook/**"
      - "base-notebook/**"
      - "datascience-notebook/**"
      - "minimal-notebook/**"
      - "pyspark-notebook/**"
      - "r-notebook/**"
      - "scipy-notebook/**"
      - "tensorflow-notebook/**"

      - "tagging/**"
      - "tests/**"
      - "requirements-dev.txt"
  push:
    branches:
      - main
      - master
    paths:
      - ".github/workflows/build-docker.yml"
      - ".github/actions/**"

      - "all-spark-notebook/**"
      - "base-notebook/**"
      - "datascience-notebook/**"
      - "minimal-notebook/**"
      - "pyspark-notebook/**"
      - "r-notebook/**"
      - "scipy-notebook/**"
      - "tensorflow-notebook/**"

      - "tagging/**"
      - "tests/**"
      - "requirements-dev.txt"
  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-base-notebook:
    name: Build base-notebook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v3
      - name: Create dev environment 📦
        uses: ./.github/actions/create-dev-env
      - name: Build image 🛠
        uses: ./.github/actions/build-push-image
        with:
          imageName: base-notebook

  test-base-notebook:
    name: Test base-notebook
    runs-on: ubuntu-latest
    needs: [build-base-notebook]
    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v3
      - name: Create dev environment 📦
        uses: ./.github/actions/create-dev-env
      - name: Download built image 📥
        uses: actions/download-artifact@v3
        with:
          name: base-notebook
          path: /tmp/
      - name: Load downloaded image to docker 📥
        run: |
          docker load --input /tmp/base-notebook.tar
          docker image ls -a
      - name: Run tests ✅
        run: python3 -m tests.run_tests --short-image-name base-notebook
