name: Build and test Docker Images

on:
  schedule:
    # Weekly, at 03:00 on Monday UTC time
    - cron: "0 3 * * 1"
  pull_request:
    paths:
      - ".github/workflows/build-docker.yml"
      - ".github/actions/**"

      - "all-spark-notebook/**"
      - "base-notebook/**"
      - "datascience-notebook/**"
      - "minimal-notebook/**"
      - "pyspark-notebook/**"
      - "r-notebook/**"
      - "scipy-notebook/**"
      - "tensorflow-notebook/**"

      - "tagging/**"
      - "tests/**"
      - "requirements-dev.txt"
  push:
    branches:
      - main
      - master
    paths:
      - ".github/workflows/build-docker.yml"
      - ".github/actions/**"

      - "all-spark-notebook/**"
      - "base-notebook/**"
      - "datascience-notebook/**"
      - "minimal-notebook/**"
      - "pyspark-notebook/**"
      - "r-notebook/**"
      - "scipy-notebook/**"
      - "tensorflow-notebook/**"

      - "tagging/**"
      - "tests/**"
      - "requirements-dev.txt"
  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-base-notebook:
    uses: ./.github/workflows/sub-build-push-image.yml
    with:
      imageName: base-notebook
      parentImageName: ""

  test-base-notebook:
    name: Test base-notebook
    runs-on: ubuntu-latest
    needs: [build-base-notebook]
    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v3
      - name: Create dev environment 📦
        uses: ./.github/actions/create-dev-env

      - name: Pull image from GitHub artifacts and test it 🛠
        uses: ./.github/actions/test-image
        with:
          imageName: base-notebook
