name: Build and test Docker Images

on:
  schedule:
    # Weekly, at 03:00 on Monday UTC time
    - cron: "0 3 * * 1"
  pull_request:
    paths:
      - ".github/workflows/build-docker.yml"
      - ".github/workflows/sub-build-upload-image.yml"
      - ".github/workflows/sub-test-images.yml"
      - ".github/actions/create-dev-env/action.yml"
      - ".github/actions/load-image/action.yml"

      - "all-spark-notebook/**"
      - "base-notebook/**"
      - "datascience-notebook/**"
      - "minimal-notebook/**"
      - "pyspark-notebook/**"
      - "r-notebook/**"
      - "scipy-notebook/**"
      - "tensorflow-notebook/**"

      - "tagging/**"
      - "tests/**"
      - "requirements-dev.txt"
  push:
    branches:
      - main
      - master
    paths:
      - ".github/workflows/build-docker.yml"
      - ".github/workflows/sub-build-upload-image.yml"
      - ".github/workflows/sub-test-images.yml"
      - ".github/actions/create-dev-env/action.yml"
      - ".github/actions/load-image/action.yml"

      - "all-spark-notebook/**"
      - "base-notebook/**"
      - "datascience-notebook/**"
      - "minimal-notebook/**"
      - "pyspark-notebook/**"
      - "r-notebook/**"
      - "scipy-notebook/**"
      - "tensorflow-notebook/**"

      - "tagging/**"
      - "tests/**"
      - "requirements-dev.txt"
  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-amd64-base:
    uses: ./.github/workflows/sub-build-upload-image.yml
    with:
      parentImage: ""
      image: base-notebook
      platform: amd64
      runsOn: ubuntu-latest

  test-amd64-base:
    needs: [build-amd64-base]
    uses: ./.github/workflows/sub-test-image.yml
    with:
      image: base-notebook
      platform: amd64
      runsOn: ubuntu-latest

  build-amd64-minimal:
    needs: [build-amd64-base]
    uses: ./.github/workflows/sub-build-upload-image.yml
    with:
      parentImage: base-notebook
      image: minimal-notebook
      platform: amd64
      runsOn: ubuntu-latest

  test-amd64-minimal:
    needs: [build-amd64-minimal]
    uses: ./.github/workflows/sub-test-images.yml
    with:
      image: minimal-notebook
      platform: amd64
      runsOn: ubuntu-latest

  amd64-images-tag-push:
    needs: [test-amd64-base, test-amd64-minimal]
    uses: ./.github/workflows/sub-tag-push-image.yml
    with:
      platform: amd64
      runsOn: ubuntu-latest
      # https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations
      # The strategy property is not supported in any job that calls a reusable workflow
      # Using the workaround: https://github.community/t/reusable-workflow-with-strategy-matrix/205676/2
      images: >-
        ["base-notebook", "minimal-notebook"]
