# This workflows purpose is to make sure we rebuild our images regularly.
#
# This workflow makes an empty commit to ensure we get a new SHA tag, and it
# explicitly dispatches the regular workflow that builds and pushes our images
# because the commit we made in this workflow can't trigger the other workflow.
#
name: Weekly rebuild dispatch

on:
  schedule:
    # weekly
    - cron: "0 0 * * 0"

jobs:
  commit-and-dispatch:
    name: Create a commit to update SHA tag and dispatch to launch Docker images build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2

      - name: Create an empty commit
        uses: stefanzweifel/git-auto-commit-action@5dd17c3b53a58c1cb5eaab903826abe94765ccd6 # dependabot updates to latest release
        with:
          commit_author: GitHub Actions <actions@github.com>
          commit_message: Empty commit to update sha tag
          commit_options: "--allow-empty"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4 # dependabot updates to latest release
        with:
          token: ${{secrets.REPO_ACCESS_TOKEN}}
          event-type: cron-docker-update
