name: Build and test x86 Docker Images

on:
  pull_request:
    paths:
      - ".github/workflows/docker-x86.yml"

      - "all-spark-notebook/**"
      - "base-notebook/**"
      - "datascience-notebook/**"
      - "minimal-notebook/**"
      - "pyspark-notebook/**"
      - "r-notebook/**"
      - "scipy-notebook/**"
      - "tensorflow-notebook/**"

      - "tagging/**"
      - "test/**"
      - "conftest.py"
      - "Makefile"
      - "pytest.ini"
      - "requirements-dev.txt"
  push:
    branches:
      - main
      - master
    paths:
      - ".github/workflows/docker-x86.yml"

      - "all-spark-notebook/**"
      - "base-notebook/**"
      - "datascience-notebook/**"
      - "minimal-notebook/**"
      - "pyspark-notebook/**"
      - "r-notebook/**"
      - "scipy-notebook/**"
      - "tensorflow-notebook/**"

      - "tagging/**"
      - "test/**"
      - "conftest.py"
      - "Makefile"
      - "pytest.ini"
      - "requirements-dev.txt"

jobs:
  build-test-x86-images:
    name: Build and test x86 Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          make -C main dev-env

      - name: Build Docker Images
        run: make -C main build-all
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain

      - name: Test Docker Images
        run: make -C main test-all
