name: Download image artifact from GitHub artifacts and test it

on:
  workflow_call:
    inputs:
      image:
        description: "Image name"
        required: true
        type: string
      platform:
        description: "Image platform"
        required: true
        type: string
      runsOn:
        description: "GitHub Actions Runner image"
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v3
      - name: Create dev environment 📦
        uses: ./.github/actions/create-dev-env

      - name: Load image to docker 📥
        uses: ./.github/actions/load-image
        with:
          image: ${{ inputs.image }}
          platform: ${{ inputs.platform }}

      - name: Run tests ✅
        run: python3 -m tests.run_tests --short-image-name ${{ inputs.image }}
        shell: bash
