name: Build Docker Images

on:
  push:
    paths-ignore:
      - "*.md"
      - "binder/**"
      - "docs/**"
      - "examples/**"

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          make dev-env lint-install
      - name: Lint Dockerfiles
        run: make lint-all
      - name: Debug python
        run: which pytest
      - name: Build Docker Images
        run: make build-test-all

  push:
    name: Push Docker Images
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: TODO
        run: echo "todo"
