name: Build Sphinx Documentation

on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/sphinx.yml"

jobs:
  build:
    name: Build Sphinx Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          make dev-env
      - name: Build Documentation
        run: make docs

  gettext:
    name: Update Translation Source Strings
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Extract Source Strings
        working-directory: docs
        run: |
          make gettext
          sphinx-intl update -p _build/gettext -l en
      - name: Push Strings to Master
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
