name: Download parent image, build new one, push it to GitHub artifacts

on:
  workflow_call:
    inputs:
      imageName:
        description: "Image name to be built"
        required: true
        type: string
      parentImageName:
        description: "Parent image name"
        required: true
        type: string
      platform:
        description: "Target platform for the built image"
        required: true
        type: string
      runsOn:
        description: "Image to be run on"
        required: true
        type: string

jobs:
  build-push-image:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v3
      - name: Create dev environment 📦
        uses: ./.github/actions/create-dev-env

      - name: Download parent built image 📥
        if: ${{ inputs.parentImageName != '' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.parentImageName }}-${{ inputs.platform }}
          path: /tmp/
      - name: Load downloaded image to docker 📥
        if: ${{ inputs.parentImageName != '' }}
        run: |
          docker load --input /tmp/${{ inputs.parentImageName }}-${{ inputs.platform }}.tar
          docker image ls -a
        shell: bash

      - name: Build image 🛠
        working-directory: ${{ inputs.imageName }}
        run: docker build --tag jupyter/${{ inputs.imageName }} --tag jupyter/${{ inputs.imageName }} .
        env:
          DOCKER_BUILDKIT: 1
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain
        shell: bash
      - name: Save image as a file 💾
        run: docker save jupyter/${{ inputs.imageName }} -o /tmp/${{ inputs.imageName }}-${{ inputs.platform }}.tar
        shell: bash

      - name: Upload artifact 💾
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.imageName }}-${{ inputs.platform }}
          path: /tmp/${{ inputs.imageName }}-${{ inputs.platform }}.tar
